[package]
name = "microservice"
version = "0.1.0"
authors = ["Miguel Lopez <miguell@cakesolutions.net>"]

[dependencies]
env_logger = "0.5.3"
futures = "0.1.17"
hyper = "0.11.13"
log = "0.4.1"
url = "1.7.0"
serde_json = "1.0.18"
diesel = { version = "1.0.0", features = ["postgres"] }
